### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by Anonimo93** [bots-business/Bots.Business.VSCode#1]
this plugin is not compatible

![error](https://user-images.githubusercontent.com/70077670/218775132-6aad4b65-dfbe-4171-be2c-b22b016c3b5d.png)

**Comment by sohamdeogaonkar** [comment]
Update your VSCode

**Comment by bots-business** [comment]
You need install it with this instruction - https://github.com/bots-business/Bots.Business.VSCode#installation
